#pragma once
#include <windows.h>
#include <string>
#include <unordered_map>

enum class Lang { CN, EN };

struct LangStrings {
    Lang lang;
    std::unordered_map<const wchar_t*, const wchar_t*> map;
};

inline Lang& ActiveLang() { static Lang l = Lang::CN; return l; }
inline void ToggleLang() { ActiveLang() = (ActiveLang() == Lang::CN) ? Lang::EN : Lang::CN; }

inline const wchar_t* LS(const wchar_t* key) {
    static LangStrings cn = { Lang::CN, {
        { L"title",           L"BorderLimited 配置工具" },
        { L"lang_toggle",     L"English" },
        { L"grp_mode",        L"窗口模式" },
        { L"fullscreen",      L"全屏" },
        { L"custom",          L"自定义" },
        { L"borderless",        L"仅去边框" },
        { L"grp_position",    L"自定义位置" },
        { L"pos_x",           L"X:" },
        { L"pos_y",           L"Y:" },
        { L"pos_w",           L"W:" },
        { L"pos_h",           L"H:" },
        { L"grp_offset",      L"裁剪偏移" },
        { L"off_l",           L"左:" },
        { L"off_t",           L"上:" },
        { L"off_r",           L"右:" },
        { L"off_b",           L"下:" },
        { L"grp_behavior",    L"窗口行为" },
        { L"should_maximize", L"最大化" },
        { L"top_most",        L"置顶" },
        { L"remove_menus",    L"移除菜单栏 (不可逆)" },
        { L"lock_cursor",     L"锁定鼠标" },
        { L"disable_winkey",  L"禁用 Win 键" },
        { L"hide_taskbar",    L"隐藏任务栏" },
        { L"hide_cursor",     L"隐藏光标" },
        { L"override_dpi",    L"覆盖 DPI 缩放" },
        { L"enable_log",      L"启用日志" },
        { L"ue3_mode",        L"UE3 模式 (D3D9 Hook)" },
        { L"grp_advanced",    L"高级" },
        { L"poll_interval",   L"轮询间隔 (ms):" },
        { L"delay_ms",        L"样式延迟 (ms):" },
        { L"ue3_res",         L"UE3 伪造分辨率:" },
        { L"monitor",         L"显示器:" },
        { L"btn_preview",     L"预览 / 拖拽定位..." },
        { L"btn_save",        L"保存" },
        { L"btn_defaults",    L"默认值" },
        { L"btn_extended",    L"扩展选项" },
        { L"title_extended",  L"扩展选项" },
        { L"grp_hotkey",      L"热键切换" },
        { L"hotkey_enable",   L"启用热键" },
        { L"btn_ok",          L"确定" },
        { L"btn_cancel",      L"取消" },
        { L"lbl_hotkey_code", L"键码 (虚拟键码):" },
        { L"lbl_hotkey_mod",  L"修饰键:" },
        { L"lbl_poll",        L"轮询 (ms):" },
        { L"lbl_delay",       L"延迟 (ms):" },
        { L"lbl_ue3res",      L"UE3 分辨率:" },
        { L"lbl_monitor",     L"显示器:" },
        { L"msg_saved",       L"BorderLimited.ini 已保存。" },

        { L"tooltip_size_full",    L"窗口自动铺满当前显示器，移除所有边框和标题栏" },
        { L"tooltip_size_custom",  L"使用下方的精确坐标 (X, Y, W, H) 来自定义窗口位置和大小。配合预览功能可拖拽定位" },
        { L"tooltip_size_borderless",L"只移除窗口边框和标题栏，保持窗口原来的位置和大小不变" },
        { L"tooltip_maximize",     L"去边框后再执行一次最大化操作 (ShowWindow SW_MAXIMIZE)，有助于某些窗口管理" },
        { L"tooltip_topmost",      L"将游戏窗口设为最顶层 (HWND_TOPMOST)，即使切换到其他程序窗口也不会被遮挡" },
        { L"tooltip_removemenus",  L"移除游戏窗口上方的 Win32 原生菜单栏 (如文件/编辑/帮助)。这个操作不可逆，关闭游戏后才能恢复" },
        { L"tooltip_lockcursor",   L"使用 ClipCursor API 将鼠标光标限制在游戏窗口内，防止双屏时鼠标飘到另一个屏幕上" },
        { L"tooltip_disablewinkey",L"通过低层键盘钩子 (WH_KEYBOARD_LL) 拦截左右 Win 键，防止游戏中误触弹出开始菜单" },
        { L"tooltip_hidetaskbar",  L"隐藏 Windows 任务栏 (Shell_TrayWnd) 并扩展桌面工作区，让窗口真正覆盖整个屏幕" },
        { L"tooltip_hidecursor",   L"将系统鼠标光标替换为完全透明的空白光标。建议配合 LockCursor 使用" },
        { L"tooltip_overridedpi",  L"禁止 Windows 对低分辨率游戏进行 DPI 虚拟化缩放。老游戏在 4K 屏上不会变模糊，但窗口可能变得很小" },
        { L"tooltip_enablelog",    L"在 ASI 插件同目录下生成 BorderLimited.log 日志文件。每次启动游戏时会清空旧日志" },
        { L"tooltip_ue3mode",      L"为虚幻引擎 3 游戏启用 D3D9 Hook 模式。拦截 SetWindowLong/SetWindowPos/CreateDevice，强制窗口化并保持全屏" },
        { L"tooltip_poll",         L"轮询检测游戏窗口的间隔时间 (毫秒)。设为 0 表示只执行一次去边框操作后停止监控" },
        { L"tooltip_delay",        L"在设置窗口样式之前等待的时间 (毫秒)。GameMaker 引擎的游戏建议设 2000。UE3 模式下的游戏不需要此设置" },
        { L"tooltip_preview",      L"打开全屏半透明预览窗口，用鼠标拖拽红色矩形来精确定位游戏窗口。Shift/Ctrl 锁轴、鼠标中键/Enter 居中、Ctrl+S 保存 Esc 取消" },

        { L"pv_info", L"窗口: %d x %d   位置: (%d, %d)\n显示器 %d: %d x %d\n边距: 左%d  上%d  右%d  下%d\n\n拖拽=移动  |  拖边=缩放\nShift=锁Y轴  |  Ctrl=锁X轴\n方向键=微调 (按住加速)\nEnter/鼠标中键=居中\nCtrl+S=保存  |  Esc=取消" },
    }};

    static LangStrings en = { Lang::EN, {
        { L"title",           L"BorderLimited Config" },
        { L"lang_toggle",     L"中文" },
        { L"grp_mode",        L"Window Mode" },
        { L"fullscreen",      L"FullScreen" },
        { L"custom",          L"Custom" },
        { L"borderless",        L"Borderless" },
        { L"grp_position",    L"Custom Position" },
        { L"pos_x",           L"X:" },
        { L"pos_y",           L"Y:" },
        { L"pos_w",           L"W:" },
        { L"pos_h",           L"H:" },
        { L"grp_offset",      L"Crop Offsets" },
        { L"off_l",           L"L:" },
        { L"off_t",           L"T:" },
        { L"off_r",           L"R:" },
        { L"off_b",           L"B:" },
        { L"grp_behavior",    L"Window Behavior" },
        { L"should_maximize", L"Maximize" },
        { L"top_most",        L"TopMost" },
        { L"remove_menus",    L"Remove Menu Bar (irreversible)" },
        { L"lock_cursor",     L"Lock Cursor" },
        { L"disable_winkey",  L"Disable Win Key" },
        { L"hide_taskbar",    L"Hide Taskbar" },
        { L"hide_cursor",     L"Hide Cursor" },
        { L"override_dpi",    L"Override DPI Scaling" },
        { L"enable_log",      L"Enable Log" },
        { L"ue3_mode",        L"UE3 Mode (D3D9 Hook)" },
        { L"grp_advanced",    L"Advanced" },
        { L"poll_interval",   L"Poll Interval (ms):" },
        { L"delay_ms",        L"Style Delay (ms):" },
        { L"ue3_res",         L"UE3 Fake Resolution:" },
        { L"monitor",         L"Monitor:" },
        { L"btn_preview",     L"Preview / Position..." },
        { L"btn_save",        L"Save" },
        { L"btn_defaults",    L"Defaults" },
        { L"btn_extended",    L"Extended" },
        { L"title_extended",  L"Extended Options" },
        { L"grp_hotkey",      L"Hotkey Toggle" },
        { L"hotkey_enable",   L"Enable Hotkey" },
        { L"btn_ok",          L"OK" },
        { L"btn_cancel",      L"Cancel" },
        { L"lbl_hotkey_code", L"Key Code (VK):" },
        { L"lbl_hotkey_mod",  L"Modifier:" },
        { L"lbl_poll",        L"Poll (ms):" },
        { L"lbl_delay",       L"Delay (ms):" },
        { L"lbl_ue3res",      L"UE3 Res:" },
        { L"lbl_monitor",     L"Monitor:" },
        { L"msg_saved",       L"BorderLimited.ini saved." },

        { L"tooltip_size_full",    L"Fill the current monitor, removing all borders and title bars" },
        { L"tooltip_size_custom",  L"Use exact coordinates (X, Y, W, H) below. Use Preview to drag-position the window" },
        { L"tooltip_size_borderless",L"Remove window borders and title only; keep the current position and size" },
        { L"tooltip_maximize",     L"Call ShowWindow(SW_MAXIMIZE) after stripping borders; helps with some window managers" },
        { L"tooltip_topmost",      L"Set HWND_TOPMOST so the game stays above other windows even when focus is lost" },
        { L"tooltip_removemenus",  L"Remove the native Win32 menu bar (File/Edit/Help). This is irreversible while the game runs" },
        { L"tooltip_lockcursor",   L"Use ClipCursor to confine the mouse to the game window. Prevents cursor drift on multi-monitor setups" },
        { L"tooltip_disablewinkey",L"Low-level keyboard hook (WH_KEYBOARD_LL) that eats left/right Windows key presses" },
        { L"tooltip_hidetaskbar",  L"Hide the Windows taskbar (Shell_TrayWnd) and expand the desktop work area" },
        { L"tooltip_hidecursor",   L"Replace the system mouse cursor with a fully transparent blank. Best used with LockCursor" },
        { L"tooltip_overridedpi",  L"Prevent Windows from DPI-blurring low-resolution games. The window may appear small on 4K screens" },
        { L"tooltip_enablelog",    L"Write BorderLimited.log next to the ASI plugin. The log is cleared at each game launch" },
        { L"tooltip_ue3mode",      L"Enable D3D9 API hooks for Unreal Engine 3 games. Intercepts SetWindowLong/SetWindowPos/CreateDevice" },
        { L"tooltip_poll",         L"Window detection polling interval in ms. Set to 0 to apply once and exit (one-shot mode)" },
        { L"tooltip_delay",        L"Delay before applying window styles, in ms. GameMaker games may need 2000. Not used when UE3 Mode is active" },
        { L"tooltip_preview",      L"Open a fullscreen semi-transparent overlay. Drag the red rect to position. Shift/Ctrl lock axes, Enter centers, Ctrl+S saves, Esc cancels" },

        { L"pv_info", L"Window: %d x %d   Position: (%d, %d)\nMonitor %d: %d x %d\nMargins: L:%d  T:%d  R:%d  B:%d\n\nDrag=move  |  Drag edge=resize\nShift=lock Y  |  Ctrl=lock X\nArrow keys=nudge (hold to accelerate)\nEnter/Middle-click=center\nCtrl+S=save  |  Esc=cancel" },
    }};

    LangStrings& tbl = (ActiveLang() == Lang::CN) ? cn : en;
    auto it = tbl.map.find(key);
    return (it != tbl.map.end()) ? it->second : key;
}
